### ISSUE TITLE
Metadata in the conversion config

### ISSUE THREAD

**Issue by m1ch4ls** [ufal/perl-pmltq#14]
This is related to #12 and #11 

I was thinking about treebank metadata and conversion workflow. Right now when I convert the treebank to pmltq I then have to go to administration and set all metadata about that treebank. Sounds simple for one - but really sucks for 20, especially when metadata are mostly the same or could be automatically generated. I can think of three options I like:

- Having metadata in treebank's database, in a special table. We could extend the config from #12 to include the metadata as well - now it's done in a similar way in config.sh
```yaml
---
data_dir: /pmltq/data/dir/
resources: /pmltq/resources/

# metadata
title: Awesome treebank
description: "...."
homepage: "https://ufal.mff.cuni.cz/"
documentation:
 - title: PDT 2.0 Manual 
   url: http://ufal.mff.cuni.cz/pdt2.0/doc/pdt-guide/en/html/ch05.html
public: true
anonymous: false

...
```

- Same as above, but metadata will be inserted to pmltq server through REST API
- The metadata will be taken from Lindat repository

I will expand this issue a little bit later

**Comment by matyaskopp** [comment]
```YAML
description: 'DESCRIPTION'
isFeatured: false
isFree: false
isPublic: false
web_api:
  dbserver: 'euler'
  password: 'PASSWORD'
  url: 'https://lindat.mff.cuni.cz/services/pmltq/'
  user: 'USERNAME'
languages:
  - got
tags:
  - PDT
test_query:
  result_dir: query_results
  queries:
    - filename: 01.svg
      query: 'a-node [];'
    - filename: 02.txt
      query: 'a-node [] >> count()'
```
added three commands:

- webdelete - remove treebank from web interface (not remove database)

- webverify - verify treebank (setted data and querying)

- webload - publish treebank

[pull request](https://github.com/ufal/perl-pmltq/pull/33)
